### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by anishagg17** [abeaumont/competitive-programming#9]
CAn you please explain why this matrix was constructed in such a way

https://github.com/abeaumont/competitive-programming/blob/1cc6c641109c6f42e9c7b2c2ad21fe5048112e7d/cses/1096.cc#L38

I know that later part will be solved by matrix exponentiation. But facing some difficulties in building the base matrix

**Comment by anishagg17** [comment]
@abeaumont PLEASE help

**Comment by anishagg17** [comment]
@abeaumont PLEASE help

**Comment by anishagg17** [comment]
@abeaumont PLEASE help

**Comment by abeaumont** [comment]
Matrix construction is derived from the linear recurrence defined by the problem, as explained at [Competitive Programmer's Handbook's Section 23.2](https://cses.fi/book/book.pdf#section.23.2)
